// Data structure
// Low-End	Mid-Range	High-End
// phone template
const template = {
    id: 0,
    category: 'Mid-Range',
    model: 'A5 2016',
    brand: 'Samsung',
    weight: 5,
    size: 4.5,
    colors: ['gold'],
    storage: 16,
    os: 'Android',
    primaryCamera: 8,
    price: 300,
    discount: 0,
}

// I am going to use phone models as my products
export const products = [
    {
        id: 0,
        category: 'High-End',
        model: 'iPhone X',
        brand: 'Apple',
        weight: 174,
        size: 5.8,
        colors: ['Space Gray', 'Silver'],
        storage: 64,
        os: 'iOS',
        primaryCamera: 12,
        price: 1179,
        discount: 10
    },
    {
        id: 1,
        category: 'High-End',
        model: 'iPhone X',
        brand: 'Apple',
        weight: 174,
        size: 5.8,
        colors: ['Space Gray', 'Silver'],
        storage: 256,
        os: 'iOS',
        primaryCamera: 12,
        price: 1359,
        discount: 0
    },
    {
        id: 2,
        category: 'High-End',
        model: 'iPhone 6',
        brand: 'Apple',
        weight: 129,
        size: 4.7,
        colors: ['Space Gray', 'Silver', 'Gold'],
        storage: 32,
        os: 'iOS',
        primaryCamera: 8,
        price: 379,
        discount: 20,
    },
    {
        id: 3,
        category: 'High-End',
        model: 'iPhone 6 Plus',
        brand: 'Apple',
        weight: 172,
        size: 5.5,
        colors: ['Space Gray', 'Silver', 'Gold'],
        storage: 16,
        os: 'iOS',
        primaryCamera: 8,
        price: 409,
        discount: 0,
    },
    {
        id: 4,
        category: 'High-End',
        model: 'iPhone 6 Plus',
        brand: 'Apple',
        weight: 172,
        size: 5.5,
        colors: ['Space Gray', 'Silver', 'Gold'],
        storage: 64,
        os: 'iOS',
        primaryCamera: 8,
        price: 429,
        discount: 0,
    },
    {
        id: 5,
        category: 'High-End',
        model: 'iPhone 6 Plus',
        brand: 'Apple',
        weight: 172,
        size: 5.5,
        colors: ['Space Gray', 'Silver', 'Gold'],
        storage: 128,
        os: 'iOS',
        primaryCamera: 8,
        price: 459,
        discount: 0,
    },
    {
        id: 6,
        category: 'High-End',
        model: 'iPhone 6s',
        brand: 'Apple',
        weight: 143,
        size: 4.7,
        colors: ['Space Gray', 'Silver', 'Gold', 'Rose Gold'],
        storage: 16,
        os: 'iOS',
        primaryCamera: 12,
        price: 399,
        discount: 5
    },
    {
        id: 7,
        category: 'High-End',
        model: 'iPhone 6s',
        brand: 'Apple',
        weight: 143,
        size: 4.7,
        colors: ['Space Gray', 'Silver', 'Gold', 'Rose Gold'],
        storage: 64,
        os: 'iOS',
        primaryCamera: 12,
        price: 399,
        discount: 5
    },
    {
        id: 8,
        category: 'High-End',
        model: 'iPhone 6s',
        brand: 'Apple',
        weight: 143,
        size: 4.7,
        colors: ['Space Gray', 'Silver', 'Gold', 'Rose Gold'],
        storage: 128,
        os: 'iOS',
        primaryCamera: 12,
        price: 399,
        discount: 5
    },
    {
        id: 9,
        category: 'High-End',
        model: 'iPhone 6s Plus',
        brand: 'Apple',
        weight: 192,
        size: 5.5,
        colors: ['Space Gray', 'Silver', 'Gold', 'Rose Gold'],
        storage: 16,
        os: 'iOS',
        primaryCamera: 12,
        price: 449,
        discount: 10,
    },
    {
        id: 10,
        category: 'High-End',
        model: 'iPhone 6s Plus',
        brand: 'Apple',
        weight: 192,
        size: 5.5,
        colors: ['Space Gray', 'Silver', 'Gold', 'Rose Gold'],
        storage: 64,
        os: 'iOS',
        primaryCamera: 12,
        price: 479,
        discount: 10,
    },
    {
        id: 11,
        category: 'High-End',
        model: 'iPhone 6s Plus',
        brand: 'Apple',
        weight: 192,
        size: 5.5,
        colors: ['Space Gray', 'Silver', 'Gold', 'Rose Gold'],
        storage: 128,
        os: 'iOS',
        primaryCamera: 12,
        price: 499,
        discount: 10,
    },
    {
        id: 12,
        category: 'High-End',
        model: 'iPhone SE',
        brand: 'Apple',
        weight: 113,
        size: 4.0,
        colors: ['Space Gray', 'Silver', 'Gold', 'Rose Gold'],
        storage: 32,
        os: 'iOS',
        primaryCamera: 12,
        price: 369,
        discount: 0
    },
    {
        id: 13,
        category: 'High-End',
        model: 'iPhone 8 Plus',
        brand: 'Apple',
        weight: '-',
        size: 5.8,
        colors: ['Jet Black', 'Black', 'Silver', 'Gold', 'Rose Gold'],
        storage: 64,
        os: 'iOS',
        primaryCamera: 12,
        price: 899,
        discount: 10
    },
    {
        id: 14,
        category: 'High-End',
        model: 'iPhone 8 Plus',
        brand: 'Apple',
        weight: '-',
        size: 5.8,
        colors: ['Jet Black', 'Black', 'Silver', 'Gold', 'Rose Gold'],
        storage: 256,
        os: 'iOS',
        primaryCamera: 12,
        price: 1109,
        discount: 5
    },
    {
        id: 15,
        category: 'High-End',
        model: 'iPhone 7 Plus',
        brand: 'Apple',
        weight: 188,
        size: 5.5,
        colors: ['Jet Black', 'Black', 'Silver', 'Gold', 'Rose Gold', 'Red'],
        storage: 32,
        os: 'iOS',
        primaryCamera: 12,
        price: 899,
        discount: 5
    },
    {
        id: 16,
        category: 'High-End',
        model: 'iPhone 7 Plus',
        brand: 'Apple',
        weight: 188,
        size: 5.5,
        colors: ['Jet Black', 'Black', 'Silver', 'Gold', 'Rose Gold', 'Red'],
        storage: 128,
        os: 'iOS',
        primaryCamera: 12,
        price: 959,
        discount: 0
    },
    {
        id: 17,
        category: 'High-End',
        model: 'iPhone 7 Plus',
        brand: 'Apple',
        weight: 188,
        size: 5.5,
        colors: ['Jet Black', 'Black', 'Silver', 'Gold', 'Rose Gold', 'Red'],
        storage: 256,
        os: 'iOS',
        primaryCamera: 12,
        price: 1009,
        discount: 10
    },
    {
        id: 18,
        category: 'High-End',
        model: 'iPhone 7',
        brand: 'Apple',
        weight: 138,
        size: 4.7,
        colors: ['Jet Black', 'Black', 'Silver', 'Gold', 'Rose Gold', 'Red'],
        storage: 32,
        os: 'iOS',
        primaryCamera: 12,
        price: 639,
        discount: 5
    },
    {
        id: 19,
        category: 'High-End',
        model: 'iPhone 7',
        brand: 'Apple',
        weight: 138,
        size: 4.7,
        colors: ['Jet Black', 'Black', 'Silver', 'Gold', 'Rose Gold', 'Red'],
        storage: 128,
        os: 'iOS',
        primaryCamera: 12,
        price: 759,
        discount: 0
    },
    {
        id: 20,
        category: 'High-End',
        model: 'iPhone 7',
        brand: 'Apple',
        weight: 138,
        size: 4.7,
        colors: ['Jet Black', 'Black', 'Silver', 'Gold', 'Rose Gold', 'Red'],
        storage: 256,
        os: 'iOS',
        primaryCamera: 12,
        price: 749,
        discount: 15,
    },
    {
        id: 21,
        category: 'High-End',
        model: 'iPhone 8',
        brand: 'Apple',
        weight: 148,
        size: 4.7,
        colors: ['Silver', 'Space Gray', 'Gold'],
        storage: 64,
        os: 'iOS',
        primaryCamera: 12,
        price: 789,
        discount: 5
    },
    {
        id: 22,
        category: 'High-End',
        model: 'iPhone 8',
        brand: 'Apple',
        weight: 148,
        size: 4.7,
        colors: ['Silver', 'Space Gray', 'Gold'],
        storage: 256,
        os: 'iOS',
        primaryCamera: 12,
        price: 889,
        discount: 10
    },
    {
        id: 23,
        category: 'High-End',
        model: 'Galaxy S8+',
        brand: 'Samsung',
        weight: 173,
        size: 6.2,
        colors: ['Midnight Black', 'Orchid Gray', 'Arctic Silver', 'Coral Blue', 'Maple Gold', 'Rose Pink'],
        storage: 128,
        os: 'Android',
        primaryCamera: 12,
        price: 700,
        discount: 0
    },
    {
        id: 24,
        category: 'High-End',
        model: 'Galaxy S8 Active',
        brand: 'Samsung',
        weight: 208,
        size: 5.8,
        colors: ['Meteor Gray', 'Tungsten Gold'],
        storage: 64,
        os: 'Android',
        primaryCamera: 12,
        price: 850,
        discount: 5
    },
    {
        id: 25,
        category: 'High-End',
        model: 'Galaxy S9',
        brand: 'Samsung',
        weight: 163,
        size: 5.8,
        colors: ['Midnight Black', 'Coral Blue', 'Titanium Gray', 'Lilac Purple', 'Burgundy Red', 'Sunrise Gold'],
        storage: 64,
        os: 'Android',
        primaryCamera: 15,
        price: 600,
        discount: 10
    },
    {
        id: 26,
        category: 'High-End',
        model: 'Galaxy S Light Luxury',
        brand: 'Samsung',
        weight: 150,
        size: 5.8,
        colors: ['Burgundy Red', 'Black Night'],
        storage: 64,
        os: 'Android',
        primaryCamera: 12,
        price: 540,
        discount: 0
    },
    {
        id: 27,
        category: 'High-End',
        model: 'Galaxy Note7 (USA)',
        brand: 'Samsung',
        weight: 169,
        size: 5.7,
        colors: ['Blue Coral', 'Silver Titanium', 'Black Onyx'],
        storage: 64,
        os: 'Android',
        primaryCamera: 12,
        price: 760,
        discount: 0
    },
    {
        id: 28,
        category: 'High-End',
        model: 'Galaxy Note8',
        brand: 'Samsung',
        weight: 195,
        size: 6.3,
        colors: ['Midnight Black', 'Maple Gold', 'Orchid Grey', 'Deep Sea Blue'],
        storage: 64,
        os: 'Android',
        primaryCamera: 12,
        price: 100,
        discount: 7
    },
    {
        id: 29,
        category: 'Mid-Range',
        model: 'Galaxy A3 (2017)',
        brand: 'Samsung',
        weight: 138,
        size: 4.7,
        colors: ['Black Sky', 'Gold Sand', 'Blue Mist', 'Peach Cloud'],
        storage: 16,
        os: 'Android',
        primaryCamera: 8,
        price: 330,
        discount: 0
    },
    {
        id: 30,
        category: 'Mid-Range',
        model: 'Galaxy A7 (2017)',
        brand: 'Samsung',
        weight: 186,
        size: 5.7,
        colors: ['Black Sky', 'Gold Sand', 'Blue Mist', 'Peach Cloud'],
        storage: 32,
        os: 'Android',
        primaryCamera: 8,
        price: 530,
        discount: 0
    },
    {
        id: 31,
        category: 'Mid-Range',
        model: 'Galaxy A5 (2017)',
        brand: 'Samsung',
        weight: 157,
        size: 5.2,
        colors: ['Black Sky', 'Gold Sand', 'Blue Mist', 'Peach Cloud'],
        storage: 32,
        os: 'Android',
        primaryCamera: 8,
        price: 430,
        discount: 5
    },
    {
        id: 32,
        category: 'Mid-Range',
        model: 'Galaxy A8 (2018)',
        brand: 'Samsung',
        weight: 172,
        size: 5.6,
        colors: ['Black, Orchid Grey, Gold, Blue'],
        storage: 32,
        os: 'Android',
        primaryCamera: 8,
        price: 430,
        discount: 3
    },
    {
        id: 33,
        category: 'Mid-Range',
        model: 'Galaxy A6 (2018)',
        brand: 'Samsung',
        weight: 159,
        size: 5.6,
        colors: ['Black', 'Gold', 'Blue', 'Lavender'],
        storage: 64,
        os: 'Android',
        primaryCamera: 8,
        price: 240,
        discount: 8
    },
    {
        id: 34,
        category: 'High-End',
        model: 'Mate 9 Pro',
        brand: 'Huawei',
        weight: 169,
        size: 5.5,
        colors: ['Haze Gold', 'Titanium Grey'],
        storage: 128,
        os: 'Android',
        primaryCamera: 12,
        price: 700,
        discount: 15
    },
    {
        id: 35,
        category: 'High-End',
        model: 'Mate 9 Porsche Design',
        brand: 'Huawei',
        weight: 169,
        size: 5.5,
        colors: ['Graphite Black'],
        storage: 256,
        os: 'Android',
        primaryCamera: 12,
        price: 1130,
        discount: 20
    },
    {
        id: 36,
        category: 'Mid-Range',
        model: 'P10',
        brand: 'Huawei',
        weight: 145,
        size: 5.1,
        colors: ['Mystic Silver', 'Rose Gold', 'Graphite Black', 'Dazzling Gold', 'Dazzling Blue', 'Greenery'],
        storage: 32,
        os: 'Android',
        primaryCamera: 8,
        price: 500,
        discount: 0
    },
    {
        id: 37,
        category: 'High-End',
        model: 'P10 Plus',
        brand: 'Huawei',
        weight: 165,
        size: 5.5,
        colors: ['Ceramic White', 'Dazzling Blue', 'Dazzling Gold', 'Graphite Black', 'Mystic Silver', 'Rose Gold', 'Greenery'],
        storage: 128,
        os: 'Android',
        primaryCamera: 12,
        price: 650,
        discount: 5
    },
    {
        id: 38,
        category: 'Low-End',
        model: 'P8 Lite (2017)',
        brand: 'Huawei',
        weight: 147,
        size: 5.2,
        colors: ['Black', 'White', 'Gold'],
        storage: 16,
        os: 'Android',
        primaryCamera: 8,
        price: 220,
        discount: 3
    },
    {
        id: 39,
        category: 'Mid-Range',
        model: 'Honor 8 Pro',
        brand: 'Huawei',
        weight: 184,
        size: 5.7,
        colors: ['Pearl White', 'Midnight Black', 'Navy Blue'],
        storage: 64,
        os: 'Android',
        primaryCamera: 8,
        price: 550,
        discount: 8
    },
    {
        id: 40,
        category: 'Low-End',
        model: 'P10 Lite',
        brand: 'Huawei',
        weight: 146,
        size: 5.2,
        colors: ['Pearl White', 'Graphite Black', 'Platinum Gold', 'Sapphire Blue'],
        storage: 64,
        os: 'Android',
        primaryCamera: 8,
        price: 280,
        discount: 15
    },
    {
        id: 41,
        category: 'Low-End',
        model: 'P9 lite mini',
        brand: 'Huawei',
        weight: 145,
        size: 5.0,
        colors: ['Silver', 'Black', 'Gold'],
        storage: 16,
        os: 'Android',
        primaryCamera: 8,
        price: 150,
        discount: 0
    },
    {
        id: 42,
        category: 'High-End',
        model: 'Mate 10 Pro',
        brand: 'Huawei',
        weight: 178,
        size: 6.0,
        colors: ['Midnight Blue', 'Titanium Gray', 'Mocha Brown', 'Pink Gold'],
        storage: 128,
        os: 'Android',
        primaryCamera: 12,
        price: 800,
        discount: 6
    },
    {
        id: 43,
        category: 'High-End',
        model: 'Mate 10 Porsche Design',
        brand: 'Huawei',
        weight: 178,
        size: 6.0,
        colors: ['Diamond Black'],
        storage: 256,
        os: 'Android',
        primaryCamera: 12,
        price: 140,
        discount: 5
    },
    {
        id: 44,
        category: 'Low-End',
        model: 'P20 lite',
        brand: 'Huawei',
        weight: 145,
        size: 5.8,
        colors: ['Klein Blue', 'Sakura Pink', 'Midnight Black'],
        storage: 32,
        os: 'Android',
        primaryCamera: 8,
        price: 370,
        discount: 10
    },
    {
        id: 45,
        category: 'High-End',
        model: 'P20',
        brand: 'Huawei',
        weight: 165,
        size: 5.8,
        colors: ['Twilight', 'Black', 'Midnight Blue', 'Pink Gold'],
        storage: 128,
        os: 'Android',
        primaryCamera: 15,
        price: 680,
        discount: 5
    },
    {
        id: 46,
        category: 'High-End',
        model: 'P20 Pro',
        brand: 'Huawei',
        weight: 180,
        size: 6.1,
        colors: ['Twilight', 'Black', 'Midnight Blue', 'Pink Gold'],
        storage: 128,
        os: 'Android',
        primaryCamera: 20,
        price: 790,
        discount: 5
    },
    {
        id: 47,
        category: 'Low-End',
        model: 'Mi 5s Plus',
        brand: 'Xiaomi',
        weight: 168,
        size: 5.7,
        colors: ['Silver', 'Gray', 'Gold', 'Rose Gold'],
        storage: 64,
        os: 'Android',
        primaryCamera: 8,
        price: 370,
        discount: 3
    },
    {
        id: 48,
        category: 'Low-End',
        model: 'Mi 5c',
        brand: 'Xiaomi',
        weight: 135,
        size: 5.1,
        colors: ['Black', 'Gold', 'Rose Gold'],
        storage: 64,
        os: 'Android',
        primaryCamera: 5,
        price: 210,
        discount: 5
    },
    {
        id: 49,
        category: 'Low-End',
        model: 'Redmi 5',
        brand: 'Xiaomi',
        weight: 157,
        size: 5.7,
        colors: ['Black', 'Gold', 'Light Blue', 'Rose Gold'],
        storage: 32,
        os: 'Android',
        primaryCamera: 9,
        price: 160,
        discount: 50
    },
    {
        id: 50,
        category: 'Low-End',
        model: 'Redmi 5A',
        brand: 'Xiaomi',
        weight: 137,
        size: 5.0,
        colors: ['Gold', 'Dark Gray', 'Rose Gold', 'Blue'],
        storage: 32,
        os: 'Android',
        primaryCamera: 7,
        price: 110,
        discount: 60
    },
    {
        id: 51,
        category: 'Low-End',
        model: 'Redmi Note 5 (Redmi 5 Plus)',
        brand: 'Xiaomi',
        weight: 180,
        size: 5.9,
        colors: ['Black', 'Gold', 'Blue', 'Rose Gold'],
        storage: 64,
        os: 'Android',
        primaryCamera: 6,
        price: 160,
        discount: 70
    }
];

export const orders = [
    {
        orderID: 0,
        customerID: 123456,
        productID: 000000,
        amount: 2,
    },
];